Fix implicit conversion warning from clang (#348)
This patches fixes the following warning (which causes compilation to fail due to `-Werror`) on `clang-802.0.38`:

```
simple_switch.cpp:38:16: error: implicit conversion from 'long' to 'int' changes value from
      2166136261 to -2128831035 [-Werror,-Wconstant-conversion]
    int hash = 2166136261;
        ~~~~   ^~~~~~~~~~
```